uisautomation/mws-panel

- mws/apimws/tests/test_bes.py
- mws/apimws/tests/test_dns.py
- mws/apimws/tests/test_snapshots.py
- mws/apimws/tests/test_vmapi.py
- mws/mws/settings_test.py
- mws/sitesmanagement/tests/test_admin_suspended.py
- mws/sitesmanagement/tests/test_vhosts.py
- mws/sitesmanagement/tests/tests.py
- mws/sitesmanagement/views/others.py
- mws/templates/mws/settings.html
It should't allow to change root mysql password as in stretch because users are added as mysql admins and have all permisions granted.
- New screen for stretch based VMs redirects to mws documentation.
- Change db root pwd view redirects to the main panel if user tries to access anyway.
- No changes for jessie based VMs.
> New MySQL view behaviour for stretch guests

- mws/apimws/migrations/0009_cluster_host.py
This PR removes the environment-specific data that we are now adding via fixtures.
> remove data in fixtures from migrations

- mws/apimws/management/commands/store_tls_files.py
mws-ansible/roles/mwsclient/tasks/tlscerts.yml expects only the vhost_id, so don't require the hash as we're not using it here anyway.
> remove unused argument

- mws/sitesmanagement/admin.py
This corrects the Recreate VM option failing on an incorrect signature of the each_context call
> correct calling signature for function

- mws/apimws/xen.py
- mws/apimws/xen_mock.py
- mws/mws/common_settings.py
- mws/mws/settings_test.py
OS_VERSION was unused and OS_VERSION_VMXENAPI was the setting that
set the OS version the panel would create VMs with. As the name
seems to be a vestige of an era where we thoughth we'd have differing
APIs for stretch and jessie, I've switched to using OS_VERSION and
deleted OS_VERSION_VMXENAPI
> replace OS_VERSION_VMXENAPI with OS_VERSION

- mws/mws/production_settings.py
This PR removes  day restrictions on checking for backup success, meaning we will check every day. Handy, as we're taking backups every day now.
> Backups every day

- mws/requirements.txt
None of the code seems to use ansible-playbook directly, but through userv, so I believe it is safe to remove.
> remove ansible dependency

- mws/templates/mws/show.html
This PR makes the panel show the Test OS upgrade button whenever there are both test and production services active, ie. when in the middle of an OS upgrade.
> add conditions to show the button when upgrading

- mws/sitesmanagement/models.py
- mws/templates/mws/show.html
It looks like not only does Django not support parentheses in {% if %} blocks, but {% with %} blocks cannot have a compound expression either. This change adds a model property function that we can use in the template and modifies the template to make use of it.
Fixes #165
> move upgrade check from template to model

- mws/templates/mws/show.html
operating system's name added to the information panel.
This pull request adds the name of the operating system to the MWS panel bellow the hostanme (e.g. Operating System: stretch)
> operating system's name added to information panel

- mws/mws/common_settings.py
- mws/sitesmanagement/views/others.py
- mws/templates/mws/clone_vm.html
This PR blocks the creation of new test VMs if there are more than a configurable amount (20 was chosen as a starting value) of them already present.
> Only allow a set number of test servers

- mws/sitesmanagement/views/sites.py
On trying to change site admin email, Django would throw ImproperlyConfigured saying:
```Specifying` both 'fields' and 'form_class' is not permitted.```
This removes fields as it's already specified in the form class itself.
> remove fields

- mws/requirements.txt
The 3.x series currently break Celery, so fix to 2.x now. Thanks to Sam and Wajdi.
> use 2.x series version of redis-py

- mws/mws/production_settings.py
because ent seems to lag a bit and backup checks tend to not find the files they need at noon.
> move job to 15:10

- Dockerfile
pip is installed as python-pip above via apt and doing this upgrade breaks it.
> do not self-upgrade pip

- mws/apimws/management/commands/ansible_inventory.py
**POTENTIALLY BREAKING CHANGE. ONLY TO BE MERGED IN COORDINATION WITH uisautomation/mws-ansible/pull/221**
Let's Encrypt will only issue certificates for hostnames it can
resolve, so we need to tell Ansible about the status of each
configured hostname.
> pass hostname status off to Ansible

- mws/mws/common_settings.py
- mws/requirements.txt
- mws/sitesmanagement/cronjobs.py
- mws/sitesmanagement/models.py
This PR adds a validator method that checks the validity of a recorded `DomainName` name. A name is considered valid if resolves to either an A or AAAA record with the respective address of the MWS service. Depending on the status of the DomainName, validation outcomes are as follows:
- `requested` names are ignored as they are handled by the `accept_it()` method
- `denied` names are ignored, it being a final state
- `external` and `special` names are checked and are set to `deleted` if they are invalid
- `accepted`, `private` and `global` names' statuses are set according to their validity returned by the resolvers configured in `MWS_RESOLVERS`. If all resolvers deny the existence of the name, it will be set to `deleted`
- `deleted` names are given a grace period of …
> Validate domains

- mws/mws/common_settings.py
- mws/sitesmanagement/models.py
The doitpoms site is behind the traffic manager because it in a sad state. This makes its hostname not resolve to a MWS address and domain validation to fail. To cope with this and future issues like it, add an MWS_ALLOWED_PROXIES setting to hold addresses that indirectly map (proxy) to the MWS and some code to include them in the validation.
> Mws proxies

- mws/apimws/management/commands/ansible_inventory.py
- mws/sitesmanagement/models.py
This PR tries to make it easier to use hostnames from Ansible by adding a dict to the inventory that holds lists of eligible hostnames keyed by the certificate provider. It also changes `ansible_ssh_host` (now deprecated) to `ansible_host`.
> Cert hostnames

- mws/mwsauth/utils.py
This PR makes us import `get_connection()` instead of the connection object `conn`, which seems to unbreak the panel.
> fix for new version of ucamlookup

- mws/mws/production_settings.py
- mws/mws/settings_developer.py
- mws/mws/settings_test.py
- mws/sitesmanagement/views/sites.py
- mws/templates/mws/show.html
This is to enable testing of dashboard features (uisautomation/mws-ansible#228 and uisautomation/mws-ansible#237)and to prepare us for the moving of Grafana from boarstall.csx to mws3-live-panel1.srv.uis (uisautomation/mws-ansible#236).
> Make metrics URL configurable

- mws/apimws/management/commands/ansible_inventory.py
- mws/sitesmanagement/models.py
**This PR requires that uisautomation/mws-ansible#244 be merged at the same time, as these two contain mutually breaking changes.**
As we'll use the various lists of hostnames in templates, it makes sense to add generating them to the Vhost model. This also removes passing down hostname status in `vhv['domains']`
> move domains list into Vhost object

- mws/requirements.txt
Fix `django-ucamlookup` at a version before 3 as it has a breaking change.
closes: #216
> Fix ucamlookup Version

- mws/requirements.txt
This makes pip install the non-binary package for psycopg2.
Fixes #218
> install from source

- mws/mws/common_settings.py
- mws/mws/production_settings.py
- mws/mws/settings_test.py
- mws/sitesmanagement/cronjobs.py
This PR adds a cronjob to remind users to delete test servers for sites that have switched to stretch and increases the number of test VMs in flight to 60.
> Test server nagger

- mws/mws/production_settings.py
- mws/mws/settings_test.py
- mws/sitesmanagement/cronjobs.py
- mws/sitesmanagement/views/others.py
This moves checking the upgrade queue and creating VMs for pending upgrades from when deleting a VM to a separate cronjob, invoked every 30 minutes, creating one instance every 30 minutes. This is so that we can work away the backlog of VMs that would otherwise not get purged from the queue.
> Periodic queue check

- mws/sitesmanagement/cronjobs.py
This makes the dequeue cronjob check whether the queued site is already on stretch and skip test site creation if it is.
Fixes #235
> do not create test server for stretch sites

- mws/sitesmanagement/views/others.py
- mws/templates/project-light/campl-mws.html
This PR changes the way site business is reported to allow users to determine which services are being configured at the moment. Fixes #223
> report service status individually

- mws/apimws/views.py
- mws/sitesmanagement/views/others.py
This removes the initial clone flag and is in tandem with the WIP changes to clonestorage.py in mws-ansible.
> WIP: Remove --initial flag

- mws/apimws/views.py
`launch_ansible_async` only does its magic if the service's status is not 'ready', and the test service is in a 'ready' state when users initiate copying the filesystem contents, so make `post_installOS` set the status to `ansible`.
> make post_installOS run Ansible
